### ISSUE TITLE
ReflectionCoefficientLocBulk with PermittivityDrude blows up at omega = 0

### ISSUE THREAD

**Issue by SiMaHer** [QuaCaTeam/quaca#49]
The reflection coefficient returns nan's for a frequency of oemga = 0. This is due the fact, that the PermittivityDrude.calculate returns a value of (-inf, nan), leading to a return value of (-nan, -nan) in ReflectionCoefficientLocBulk.calculate

**Comment by myoelmy** [comment]
Used scaled permittivities to fix the bug.
